#pragma once
#include "cpu_state.h"

/* Declarations for functions generated by the snesrecomp recompiler.
 * These are auto-discovered from the SNES interrupt vector table and
 * compiled into the generated bank C files. */

/* Interrupt handlers — auto-discovered from the SNES vector table at
 * $00:FFE0-FFFF. Each takes a CpuState* and mutates it in place. */
void I_RESET(CpuState *cpu);
void I_NMI(CpuState *cpu);
void I_IRQ(CpuState *cpu);

/* Watchdog hook called at every block label in generated code.
 * Implemented in snesrecomp/runner/src/common_cpu_infra.c. */
void WatchdogCheck(void);
